// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPh23dAMiZ4Z9uXBguHlfyKSneYWxrAi0',
    appId: '1:227376069500:web:551c82d260f434bf5742f9',
    messagingSenderId: '227376069500',
    projectId: 'todo-book-7382a',
    authDomain: 'todo-book-7382a.firebaseapp.com',
    storageBucket: 'todo-book-7382a.appspot.com',
    measurementId: 'G-8K74DWMFQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKx0_3ABGxuJxwAycjrpvMQRxqHROt5r8',
    appId: '1:227376069500:android:65abd5ca16ec1af35742f9',
    messagingSenderId: '227376069500',
    projectId: 'todo-book-7382a',
    storageBucket: 'todo-book-7382a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxbVU8cT9H2MGMcGr-gxWJtNqXU0O1PfE',
    appId: '1:227376069500:ios:bbbd0a2bfc00fc025742f9',
    messagingSenderId: '227376069500',
    projectId: 'todo-book-7382a',
    storageBucket: 'todo-book-7382a.appspot.com',
    iosBundleId: 'com.example.todo',
  );
}
